# Generated by Django 2.2.16 on 2021-12-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211213_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
