# Generated by Django 2.2.16 on 2021-12-16 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20211216_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Не корректный slug', regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
