# Generated by Django 2.2.16 on 2021-12-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
