# Generated by Django 2.2.16 on 2021-12-13 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211210_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Не корректный никнейм', regex='^[\\w.@+-]+$')], verbose_name='Никнейм'),
        ),
    ]
