# Generated by Django 2.2.16 on 2021-12-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211215_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_subscribed',
        ),
    ]
